unlink("analysis/cache/about.Rmd", recursive = TRUE)
unlink("docs/figure/about.Rmd", recursive = TRUE)
unlink("docs/about.html")
wflow_build(files = "analysis/about.Rmd")

unlink("analysis/cache/index.Rmd", recursive = TRUE)
unlink("docs/figure/index.Rmd", recursive = TRUE)
unlink("docs/index.html")
wflow_build(files = "analysis/index.Rmd")

unlink("analysis/cache/license.Rmd", recursive = TRUE)
unlink("docs/figure/license.Rmd", recursive = TRUE)
unlink("docs/license.html")
wflow_build(files = "analysis/license.Rmd")

unlink("analysis/cache/01-quality-control.Rmd", recursive = TRUE)
unlink("docs/figure/01-quality-control.Rmd", recursive = TRUE)
unlink("output/01-quality-control.rds")
unlink("docs/01-quality-control.html")
wflow_build(files = "analysis/01-quality-control.Rmd")

unlink("analysis/cache/02-normalization.Rmd", recursive = TRUE)
unlink("docs/figure/02-normalization.Rmd", recursive = TRUE)
unlink("output/02-normalization.rds")
unlink("docs/02-normalization.html")
wflow_build(files = "analysis/02-normalization.Rmd")

unlink("analysis/cache/03-feature-selection.Rmd", recursive = TRUE)
unlink("docs/figure/03-feature-selection.Rmd", recursive = TRUE)
unlink("output/03-feature-selection.rds")
unlink("docs/03-feature-selection.html")
wflow_build(files = "analysis/03-feature-selection.Rmd")

unlink("analysis/cache/04-reduced-dimensions.Rmd", recursive = TRUE)
unlink("docs/figure/04-reduced-dimensions.Rmd", recursive = TRUE)
unlink("output/04-reduced-dimensions.rds")
unlink("docs/04-reduced-dimensions.html")
wflow_build(files = "analysis/04-reduced-dimensions.Rmd")

unlink("analysis/cache/05-clustering.Rmd", recursive = TRUE)
unlink("docs/figure/05-clustering.Rmd", recursive = TRUE)
unlink("output/05-clustering.rds")
unlink("docs/05-clustering.html")
wflow_build(files = "analysis/05-clustering.Rmd")

unlink("analysis/cache/06-doublet-detection.Rmd", recursive = TRUE)
unlink("docs/figure/06-doublet-detection.Rmd", recursive = TRUE)
unlink("output/06-doublet-detection.rds")
unlink("docs/06-doublet-detection.html")
wflow_build(files = "analysis/06-doublet-detection.Rmd")

unlink("analysis/cache/07-cell-cycle.Rmd", recursive = TRUE)
unlink("docs/figure/07-cell-cycle.Rmd", recursive = TRUE)
unlink("output/07-cell-cycle.rds")
unlink("docs/07-cell-cycle.html")
wflow_build(files = "analysis/07-cell-cycle.Rmd")

unlink("analysis/cache/08-marker-detection.Rmd", recursive = TRUE)
unlink("docs/figure/08-marker-detection.Rmd", recursive = TRUE)
unlink("output/08-marker-detection.rds")
unlink("docs/08-marker-detection.html")
wflow_build(files = "analysis/08-marker-detection.Rmd")

unlink("analysis/cache/09-cell-annotation.Rmd", recursive = TRUE)
unlink("docs/figure/09-cell-annotation.Rmd", recursive = TRUE)
unlink("output/09-cell-annotation.rds")
unlink("docs/09-cell-annotation.html")
wflow_build(files = "analysis/09-cell-annotation.Rmd")

unlink("analysis/cache/10-atlas-integration.Rmd", recursive = TRUE)
unlink("docs/figure/10-atlas-integration.Rmd", recursive = TRUE)
unlink("output/10-atlas-integration.rds")
unlink("docs/10-atlas-integration.html")
wflow_build(files = "analysis/10-atlas-integration.Rmd")

unlink("analysis/cache/11-atlas-neighbors.Rmd", recursive = TRUE)
unlink("docs/figure/11-atlas-neighbors.Rmd", recursive = TRUE)
unlink("output/11-atlas-neighbors.rds")
unlink("docs/11-atlas-neighbors.html")
wflow_build(files = "analysis/11-atlas-neighbors.Rmd")

unlink("analysis/cache/12-atlas-trajectory.Rmd", recursive = TRUE)
unlink("docs/figure/12-atlas-trajectory.Rmd", recursive = TRUE)
unlink("output/12-atlas-trajectory.rds")
unlink("docs/12-atlas-trajectory.html")
wflow_build(files = "analysis/12-atlas-trajectory.Rmd")

unlink("analysis/cache/13-atlas-clustering.Rmd", recursive = TRUE)
unlink("docs/figure/13-atlas-clustering.Rmd", recursive = TRUE)
unlink("output/13-atlas-clustering.rds")
unlink("docs/13-atlas-clustering.html")
wflow_build(files = "analysis/13-atlas-clustering.Rmd")

unlink("analysis/cache/14-atlas-markers.Rmd", recursive = TRUE)
unlink("docs/figure/14-atlas-markers.Rmd", recursive = TRUE)
unlink("output/14-atlas-markers.rds")
unlink("docs/14-atlas-markers.html")
wflow_build(files = "analysis/14-atlas-markers.Rmd")

unlink("analysis/cache/15-scenic-analysis.Rmd", recursive = TRUE)
unlink("docs/figure/15-scenic-analysis.Rmd", recursive = TRUE)
unlink("output/15-scenic-analysis.rds")
unlink("docs/15-scenic-analysis.html")
wflow_build(files = "analysis/15-scenic-analysis.Rmd")

unlink("analysis/cache/16-geneset-activity.Rmd", recursive = TRUE)
unlink("docs/figure/16-geneset-activity.Rmd", recursive = TRUE)
unlink("output/16-geneset-activity.rds")
unlink("docs/16-geneset-activity.html")
wflow_build(files = "analysis/16-geneset-activity.Rmd")

unlink("analysis/cache/17-haystack-analysis.Rmd", recursive = TRUE)
unlink("docs/figure/17-haystack-analysis.Rmd", recursive = TRUE)
unlink("output/17-haystack-analysis.rds")
unlink("docs/17-haystack-analysis.html")
wflow_build(files = "analysis/17-haystack-analysis.Rmd")

unlink("analysis/cache/18-cell-exploration.Rmd", recursive = TRUE)
unlink("docs/figure/18-cell-exploration.Rmd", recursive = TRUE)
unlink("output/18-cell-exploration.rds")
unlink("docs/18-cell-exploration.html")
wflow_build(files = "analysis/18-cell-exploration.Rmd")

unlink("analysis/cache/19-cell-heterogeneity.Rmd", recursive = TRUE)
unlink("docs/figure/19-cell-heterogeneity.Rmd", recursive = TRUE)
unlink("output/19-cell-heterogeneity.rds")
unlink("docs/19-cell-heterogeneity.html")
wflow_build(files = "analysis/19-cell-heterogeneity.Rmd")

unlink("analysis/cache/interactive.Rmd", recursive = TRUE)
unlink("docs/figure/interactive.Rmd", recursive = TRUE)
unlink("output/interactive.rds")
unlink("docs/interactive.html")
wflow_build(files = "analysis/interactive.Rmd")
